rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - jruby-19mode
  - jruby-1.7.23
  - jruby-9.0.4.0

matrix:
  allow_failures:
    - rvm: 1.9.3

env:
  - PATH=$PATH:$HOME/gradle/bin:$HOME/rebar:$HOME/go/bin GOPATH=$HOME/go

notifications:
  email:
    - licensefinder@pivotallabs.com
  webhooks:
    urls:
    - http://pulse.pivotallabs.com/projects/657d35b7-b896-4bf3-8837-9d558e2ab651/status
    on_start: true

before_install:
  - .travis/install_gradle.sh
  - .travis/install_rebar.sh
  - .travis/install_bower.sh
  - .travis/install_godep.sh

script:
  - rake install
  - rake spec
  - rake features
